#!/bin/bash

# MAIN
main() {
    python3 -m venv .venv
    source .venv/bin/activate
    cd app || exit
    pip3 install -r requirements #--force-reinstall
    ./main.py "$@" 
    deactivate
}

main "$@"
