apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ace
  name: ace
spec:
  containers:
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - controller
    image: localhost/ace_prototype:latest
    name: controller
    ports:
    - containerPort: 2349
      hostPort: 2349
    volumeMounts:
    - mountPath: /home/ace/storage/controller
      name: ace_controller_volume
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - queue
    image: localhost/ace_prototype:latest
    name: queue
    ports:
    - containerPort: 4222
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - model_provider
    image: localhost/ace_prototype:latest
    name: model_provider
    ports:
    - containerPort: 4223
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - telemetry
    image: localhost/ace_prototype:latest
    name: telemetry
    ports:
    - containerPort: 4931
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - actions
    image: localhost/ace_prototype:latest
    name: actions
    ports:
    - containerPort: 4932
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - memory
    image: localhost/ace_prototype:latest
    name: memory
    ports:
    - containerPort: 4933
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - aspirational
    image: localhost/ace_prototype:latest
    name: aspirational
    ports:
    - containerPort: 4581
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - global_strategy
    image: localhost/ace_prototype:latest
    name: global_strategy
    ports:
    - containerPort: 4582
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - agent_model
    image: localhost/ace_prototype:latest
    name: agent_model
    ports:
    - containerPort: 4583
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - executive_function
    image: localhost/ace_prototype:latest
    name: executive_function
    ports:
    - containerPort: 4584
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - cognitive_control
    image: localhost/ace_prototype:latest
    name: cognitive_control
    ports:
    - containerPort: 4585
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
  - command:
    - python3
    - main.py
    - -sb
    - -ct
    - task_prosecution
    image: localhost/ace_prototype:latest
    name: task_prosecution
    ports:
    - containerPort: 4586
    volumeMounts:
    - mountPath: /home/ace/storage/layers
      name: ace_layers_volume
    - mountPath: /home/ace/storage/output
      name: ace_output_volume
  volumes:
  - hostPath:
      path: /Users/jason/programming/personal_projects/ace_prototype/app/storage/controller
      type: Directory
    name: ace_controller_volume
  - hostPath:
      path: /Users/jason/programming/personal_projects/ace_prototype/app/storage/layers
      type: Directory
    name: ace_layers_volume
  - hostPath:
      path: /Users/jason/programming/personal_projects/ace_prototype/app/storage/output
      type: Directory
    name: ace_output_volume
    
