FROM python:alpine

COPY . /home/ace

RUN apk add --no-cache bash build-base libffi-dev python3-dev nats-server && \
    pip3 install -r /home/ace/requirements && \
    apk del build-base libffi-dev python3-dev && \
    rm -rf /var/cache/apk/*

WORKDIR /home/ace

ENTRYPOINT ["python3", "main.py"]