apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ ace_pod_name }}
  name: {{ ace_pod_name }}
spec:
  containers:
  - command:
    - {{ start_command }}
    - {{ controller_name }}
    image: {{ ace_image_name }}
    name: {{ controller_name }}
    ports:
    - containerPort: {{ controller_port }}
      hostPort: {{ controller_port }}
    volumeMounts:
    - mountPath: {{ controller_container_path }}
      name: {{ controller_volume }}
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ queue_name }}
    image: {{ ace_image_name }}
    name: {{ queue_name }}
    ports:
    - containerPort: {{ queue_port }}
  - command:
    - {{ start_command }}
    - {{ model_provider_name }}
    image: {{ ace_image_name }}
    name: {{ model_provider_name }}
    ports:
    - containerPort: {{ model_provider_port }}
  - command:
    - {{ start_command }}
    - {{ telemetry_name }}
    image: {{ ace_image_name }}
    name: {{ telemetry_name }}
    ports:
    - containerPort: {{ telemetry_port }}
  - command:
    - {{ start_command }}
    - {{ actions_name }}
    image: {{ ace_image_name }}
    name: {{ actions_name }}
    ports:
    - containerPort: {{ actions_port }}
  - command:
    - {{ start_command }}
    - {{ memory_name }}
    image: {{ ace_image_name }}
    name: {{ memory_name }}
    ports:
    - containerPort: {{ memory_port }}
  - command:
    - {{ start_command }}
    - {{ aspirational_name }}
    image: {{ ace_image_name }}
    name: {{ aspirational_name }}
    ports:
    - containerPort: {{ aspirational_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ global_strategy_name }}
    image: {{ ace_image_name }}
    name: {{ global_strategy_name }}
    ports:
    - containerPort: {{ global_strategy_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ agent_model_name }}
    image: {{ ace_image_name }}
    name: {{ agent_model_name }}
    ports:
    - containerPort: {{ agent_model_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ executive_function_name }}
    image: {{ ace_image_name }}
    name: {{ executive_function_name }}
    ports:
    - containerPort: {{ executive_function_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ cognitive_control_name }}
    image: {{ ace_image_name }}
    name: {{ cognitive_control_name }}
    ports:
    - containerPort: {{ cognitive_control_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
  - command:
    - {{ start_command }}
    - {{ task_prosecution_name }}
    image: {{ ace_image_name }}
    name: {{ task_prosecution_name }}
    ports:
    - containerPort: {{ task_prosecution_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ output_container_path }}
      name: {{ output_volume }}
  volumes:
  - hostPath:
      path: {{ controller_host_path }}
      type: Directory
    name: {{ controller_volume }}
  - hostPath:
      path: {{ layers_host_path }}
      type: Directory
    name: {{ layers_volume }}
  - hostPath:
      path: {{ output_host_path }}
      type: Directory
    name: {{ output_volume }}
    
